//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Studio {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class StudioSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static StudioSettings defaultInstance = ((StudioSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new StudioSettings())));
        
        public static StudioSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size Size {
            get {
                return ((global::System.Drawing.Size)(this["Size"]));
            }
            set {
                this["Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BlackboardExpand {
            get {
                return ((string)(this["BlackboardExpand"]));
            }
            set {
                this["BlackboardExpand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LoadLastSolution {
            get {
                return ((bool)(this["LoadLastSolution"]));
            }
            set {
                this["LoadLastSolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlackboardToolTips {
            get {
                return ((bool)(this["BlackboardToolTips"]));
            }
            set {
                this["BlackboardToolTips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Browser\\AspireBrowser.Asln")]
        public string LastSolutionFileName {
            get {
                return ((string)(this["LastSolutionFileName"]));
            }
            set {
                this["LastSolutionFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Leaf")]
        public string BlackboardGeneratedCaptionRule {
            get {
                return ((string)(this["BlackboardGeneratedCaptionRule"]));
            }
            set {
                this["BlackboardGeneratedCaptionRule"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$(MyDocuments)\\AspireStudio Solutions\\")]
        public string DefaultSolutionDirectory {
            get {
                return ((string)(this["DefaultSolutionDirectory"]));
            }
            set {
                this["DefaultSolutionDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ToolBox")]
        public string ToolBoxFileName {
            get {
                return ((string)(this["ToolBoxFileName"]));
            }
            set {
                this["ToolBoxFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MessageLogResumes {
            get {
                return ((bool)(this["MessageLogResumes"]));
            }
            set {
                this["MessageLogResumes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VariableValue,Last2\r\nCommandMessage,Last2\r\nDataMessage,Last2\r\nDataReplyMessage,La" +
            "st2")]
        public string MonitorCaptionRules {
            get {
                return ((string)(this["MonitorCaptionRules"]));
            }
            set {
                this["MonitorCaptionRules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FindComponentWithWholeAddress {
            get {
                return ((bool)(this["FindComponentWithWholeAddress"]));
            }
            set {
                this["FindComponentWithWholeAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Plugins.xml")]
        public string PluginConfigFile {
            get {
                return ((string)(this["PluginConfigFile"]));
            }
            set {
                this["PluginConfigFile"] = value;
            }
        }
    }
}
